# Generated by Django 3.0.7 on 2020-08-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='base_exp',
            field=models.IntegerField(default=19),
            preserve_default=False,
        ),
    ]
