# Generated by Django 3.0.7 on 2020-08-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemon_base_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='cost',
            field=models.IntegerField(default=45),
        ),
    ]
