# Generated by Django 3.0.7 on 2020-08-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_pokemon_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='user_defined',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
