# Generated by Django 3.0.7 on 2020-08-06 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_auto_20200806_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='double_damage_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='double_damage_from_set', to='pokemon.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='double_damage_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='double_damage_to_set', to='pokemon.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='half_damage_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='half_damage_from_set', to='pokemon.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='half_damage_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='half_damage_to_set', to='pokemon.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='no_damage_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_damage_from_set', to='pokemon.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='no_damage_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_damage_to_set', to='pokemon.Type'),
        ),
    ]
