# Generated by Django 3.0.7 on 2020-08-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_auto_20200806_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='double_damage_from',
        ),
        migrations.AddField(
            model_name='type',
            name='double_damage_from',
            field=models.ManyToManyField(blank=True, null=True, related_name='_type_double_damage_from_+', to='pokemon.Type'),
        ),
        migrations.RemoveField(
            model_name='type',
            name='double_damage_to',
        ),
        migrations.AddField(
            model_name='type',
            name='double_damage_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='_type_double_damage_to_+', to='pokemon.Type'),
        ),
        migrations.RemoveField(
            model_name='type',
            name='half_damage_from',
        ),
        migrations.AddField(
            model_name='type',
            name='half_damage_from',
            field=models.ManyToManyField(blank=True, null=True, related_name='_type_half_damage_from_+', to='pokemon.Type'),
        ),
        migrations.RemoveField(
            model_name='type',
            name='half_damage_to',
        ),
        migrations.AddField(
            model_name='type',
            name='half_damage_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='_type_half_damage_to_+', to='pokemon.Type'),
        ),
        migrations.RemoveField(
            model_name='type',
            name='no_damage_from',
        ),
        migrations.AddField(
            model_name='type',
            name='no_damage_from',
            field=models.ManyToManyField(blank=True, null=True, related_name='_type_no_damage_from_+', to='pokemon.Type'),
        ),
        migrations.RemoveField(
            model_name='type',
            name='no_damage_to',
        ),
        migrations.AddField(
            model_name='type',
            name='no_damage_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='_type_no_damage_to_+', to='pokemon.Type'),
        ),
    ]
