# Generated by Django 3.0.7 on 2020-08-06 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_auto_20200806_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='double_damage_from',
            field=models.ManyToManyField(blank=True, null=True, related_name='double_damage_from_set', to='pokemon.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='double_damage_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='double_damage_to_set', to='pokemon.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='half_damage_from',
            field=models.ManyToManyField(blank=True, null=True, related_name='half_damage_from_set', to='pokemon.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='half_damage_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='half_damage_to_set', to='pokemon.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='no_damage_from',
            field=models.ManyToManyField(blank=True, null=True, related_name='no_damage_from_set', to='pokemon.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='no_damage_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='no_damage_to_set', to='pokemon.Type'),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_pokemon', to='pokemon.Type')),
                ('to_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_pokemon', to='pokemon.Type')),
            ],
        ),
    ]
