# Generated by Django 3.0.7 on 2020-08-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0009_auto_20200806_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprite',
            name='name',
            field=models.CharField(default=1, help_text='name of the pokemon this set of sprites belongs to', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat',
            name='name',
            field=models.CharField(default=1, help_text='name of the pokemon this set of stats belongs to', max_length=30),
            preserve_default=False,
        ),
    ]
