# Generated by Django 3.0.7 on 2020-08-12 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemon', '0011_auto_20200807_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('pokemons_created', models.ManyToManyField(related_name='pokemons_created', to='pokemon.Pokemon')),
                ('pokemons_owned', models.ManyToManyField(related_name='pokemons_owned', to='pokemon.Pokemon')),
                ('pokemons_team', models.ManyToManyField(related_name='pokemons_team', to='pokemon.Pokemon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
