# Generated by Django 3.0.7 on 2020-08-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pokemons_created',
            field=models.ManyToManyField(blank=True, related_name='pokemons_created', to='pokemon.Pokemon'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pokemons_owned',
            field=models.ManyToManyField(blank=True, related_name='pokemons_owned', to='pokemon.Pokemon'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pokemons_team',
            field=models.ManyToManyField(blank=True, related_name='pokemons_team', to='pokemon.Pokemon'),
        ),
    ]
