# Generated by Django 3.0.7 on 2020-08-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0013_auto_20200812_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprite',
            name='back_default',
            field=models.URLField(blank=True, max_length=300, verbose_name='default back url'),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='front_default',
            field=models.URLField(blank=True, max_length=300, verbose_name='default back url'),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='name',
            field=models.CharField(blank=True, help_text='name of the pokemon this set of sprites belongs to', max_length=30),
        ),
        migrations.AlterField(
            model_name='sprite',
            name='svg_sprite',
            field=models.URLField(blank=True, max_length=300, verbose_name='default back url'),
        ),
    ]
